server:
  port: 8087

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    a.path: /a/**
    a.serviceId: eureka-tds
    a.retryable: true

